- name: Configure repo for containerd
  become: yes
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: reset k8s
  become: yes
  shell: kubeadm reset --force

- name: De-install conflicting packages for containerd
  become: yes
  dnf:
    name: "{{ item }}"
    state: absent
  loop:
    - podman
    - cri-o
    - runc

- name: Install Containerd packages
  become: yes
  dnf:
    name: "{{ CONTAINERD_PACKAGE_LIST }}"
    state: latest

- name: Install Containerd packages
  become: yes
  dnf:
    name: "iproute-tc"
    state: latest


