- name: Add key for Containerd repo
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Containerd repo
  become: yes
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null


- name: Install Containerd packages
  become: yes
  apt:
    name: "{{ CONTAINERD_PACKAGE_LIST }}"
    state: latest
    update_cache: true
